version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: barcode_db
      POSTGRES_USER: barcode_user
      POSTGRES_PASSWORD: barcode_pass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U barcode_user -d barcode_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      DATABASE_URL: postgresql://barcode_user:barcode_pass@db:5432/barcode_db
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - .:/app
    command: >
      sh -c "
        echo 'Initializing database...' &&
        python init_db.py &&
        echo 'Starting application...' &&
        gunicorn --bind 0.0.0.0:8080 app:app
      "

volumes:
  postgres_data: